
import type { Quote, Exercise, Hospital, FASTStep, HealthcareService, Nurse, Doctor, ConsultationType, PharmacyProduct } from '@/types';
import { Smile, Users, MessageSquare, Clock, UserRoundPlus, Home, Video, Truck, TestTube2, Pill } from 'lucide-react';

export const motivationalQuotes: Quote[] = [
  { id: '1', text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { id: '2', text: "Your present circumstances don't determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { id: '3', text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { id: '4', text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { id: '5', text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas A. Edison" },
  { id: '6', text: "Recovery is not one and done. It's a lifelong journey that takes place one day, one step at a time.", author: "Unknown" },
  { id: '7', text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" }
];

export const rehabilitationExercises: Exercise[] = [
  {
    id: '1',
    name: 'Arm Raises (Shoulder Flexion)',
    description: 'Helps improve shoulder mobility and strength.',
    instructions: [
      'Sit or stand tall with your arm by your side.',
      'Slowly raise your affected arm forward and up towards the ceiling as far as comfortable.',
      'Hold for 2-3 seconds.',
      'Slowly lower your arm back down.',
      'Repeat 10-15 times.'
    ],
    videoUrl: 'https://www.youtube.com/results?search_query=Arm+Raises+%28Shoulder+Flexion%29+stroke+rehabilitation+exercise+guide',
  },
  {
    id: '2',
    name: 'Wrist Bends (Wrist Flexion/Extension)',
    description: 'Aids in regaining wrist flexibility and control.',
    instructions: [
      'Rest your forearm on a table with your hand hanging off the edge, palm up.',
      'Slowly bend your wrist upwards, bringing your fingers towards you.',
      'Hold for 2-3 seconds.',
      'Slowly lower your wrist back to the starting position.',
      'Turn your palm down and repeat, bending your wrist upwards.',
      'Repeat each direction 10-15 times.'
    ],
    videoUrl: 'https://www.youtube.com/results?search_query=Wrist+Bends+%28Wrist+Flexion%2FExtension%29+stroke+rehabilitation+exercise+guide',
  },
  {
    id: '3',
    name: 'Sit to Stand',
    description: 'Improves leg strength and balance, essential for walking.',
    instructions: [
      'Sit on a sturdy chair with your feet flat on the floor.',
      'Lean forward slightly and push through your heels to stand up.',
      'Stand tall for a moment.',
      'Slowly lower yourself back to a seated position.',
      'Repeat 10-15 times.'
    ],
    videoUrl: 'https://www.youtube.com/results?search_query=Sit+to+Stand+stroke+rehabilitation+exercise+guide',
  },
  {
    id: '4',
    name: 'Finger Taps',
    description: 'Enhances fine motor skills and finger dexterity.',
    instructions: [
      'Rest your hand on a flat surface, palm down.',
      'Tap each finger one at a time against your thumb, starting with your index finger.',
      'Go through all fingers, then reverse the order.',
      'Alternatively, tap each finger on the table surface.',
      'Repeat 10-15 cycles.'
    ],
    videoUrl: 'https://www.youtube.com/results?search_query=Finger+Taps+stroke+rehabilitation+exercise+guide',
  },
  {
    id: '5',
    name: 'Seated Trunk Twists',
    description: 'Improves core strength and flexibility of the spine.',
    instructions: [
      'Sit tall in a chair with your feet flat on the floor and knees bent at 90 degrees.',
      'Place your hands on your shoulders or across your chest.',
      'Slowly twist your upper body to one side as far as comfortable, keeping your hips stable.',
      'Hold for 2-3 seconds.',
      'Return to the center and then twist to the other side.',
      'Repeat 10-15 times to each side.'
    ],
    videoUrl: 'https://www.youtube.com/results?search_query=Seated+Trunk+Twists+stroke+rehabilitation+exercise+guide',
  },
  {
    id: '6',
    name: 'Ankle Pumps',
    description: 'Helps improve circulation and range of motion in the ankles.',
    instructions: [
      'Sit or lie down with your legs extended.',
      'Gently point your toes away from you (plantarflexion).',
      'Hold for 2-3 seconds.',
      'Then, pull your toes towards you, flexing your ankle (dorsiflexion).',
      'Hold for 2-3 seconds.',
      'Repeat 15-20 times for each ankle.'
    ],
    videoUrl: 'https://www.youtube.com/results?search_query=Ankle+Pumps+stroke+rehabilitation+exercise+guide',
  }
];

export const fastTestSteps: FASTStep[] = [
  {
    id: 'F',
    title: 'Face Drooping',
    description: 'Does one side of the face droop or is it numb?',
    checkItems: ['Ask the person to smile.', 'Is the smile uneven or lopsided?'],
    details: 'Facial drooping, especially on one side, is a common sign of a stroke. The inability to make a symmetrical smile can indicate muscle weakness caused by the stroke.',
    icon: Smile,
  },
  {
    id: 'A',
    title: 'Arm Weakness',
    description: 'Is one arm weak or numb?',
    checkItems: ['Ask the person to raise both arms.', 'Does one arm drift downward or is unable to rise?'],
    details: 'Sudden weakness or numbness in one arm is another key indicator. If one arm drifts down when both are raised, it could signal a stroke.',
    icon: Users,
  },
  {
    id: 'S',
    title: 'Speech Difficulty',
    description: 'Is speech slurred, are they unable to speak, or are they hard to understand?',
    checkItems: ['Ask the person to repeat a simple sentence, like "The sky is blue."', 'Is the sentence repeated correctly? Is their speech slurred or strange?'],
    details: 'Difficulty speaking, slurred speech, or inability to understand speech can be symptoms of a stroke. Pay attention to any sudden changes in communication.',
    icon: MessageSquare,
  },
  {
    id: 'T',
    title: 'Time to call Emergency Services',
    description: 'If you observe any of these signs, it’s time to call emergency services immediately.',
    checkItems: ['Note the time when the first symptoms appeared.', 'Call emergency services (e.g., 112) right away.'],
    details: 'Time is critical in stroke treatment. The sooner a person receives medical attention, the better their chances of recovery. Do not delay in calling for help.',
    icon: Clock,
  },
];


export const sampleHospitals: Hospital[] = [
  {
    id: '1',
    name: 'Olive Hospital - Hyderabad',
    address: 'Masab Tank, Main Road, Chintal Basti, Hyderabad, Telangana 500028, India',
    phone: '+91 40 2351 5000',
    services: ['Multi-Speciality Care', 'Emergency Services', 'Diagnostics & Imaging', 'Stroke Unit'],
    imageUrl: '/olive.webp',
    imageHint: 'modern hospital hyderabad',
  },
  {
    id: '2',
    name: 'Premier Hospital - Hyderabad',
    address: 'H.No: 12-2-823/A/25, St Ann\'s School Road, Opp: R.T.A Office, Humayun Nagar, Mehdipatnam, Hyderabad, Telangana 500028, India',
    phone: '+91 40 2353 8686',
    services: ['General Medicine', 'Orthopedics', 'Neurology Consultations', '24/7 Pharmacy'],
    imageUrl: '/premier.jpeg',
    imageHint: 'hospital hyderabad',
  },
  {
    id: '3',
    name: 'Sarojini Devi Hospital - Hyderabad',
    address: 'Santhosh Nagar, Mehdipatnam, Hyderabad, Telangana 500028, India',
    phone: '+91 40 2334 0119',
    services: ['Specialized Eye Care', 'Emergency Eye Services', 'Outpatient Department'],
    imageUrl: '/sarojini.avif',
    imageHint: 'eye hospital hyderabad',
  },
   {
    id: '4',
    name: 'Ayaan Hospital - Hyderabad',
    address: '12-2-417/A/2, Main Road, beside Subhash Chandra Bose Statue, near NMDC, Gudimalkapur, Mehdipatnam, Hyderabad, Telangana 500028, India',
    phone: '+91 72073 57861',
    services: ['Multi-Speciality Services', 'Intensive Care Unit', 'Surgical Facilities'],
    imageUrl: '/ayaan.png',
    imageHint: 'multi-speciality hospital hyderabad',
  },
  {
    id: '5',
    name: 'Bombay Hospital & Medical Research Centre - Mumbai',
    address: '12, Vitthaldas Thackersey Marg, New Marine Lines, Mumbai, Maharashtra 400020, India',
    phone: '+91 22 2206 7676',
    services: ['Emergency Care', 'Cardiology', 'Neurology', 'Advanced Stroke Care'],
    imageUrl: '/bombay.jpg',
    imageHint: 'city hospital building mumbai',
  },
  {
    id: '6',
    name: 'Max Healthcare Saket - Delhi',
    address: 'Max Super Speciality Hospital, Press Enclave Road, Saket Institutional Area, Saket, New Delhi, Delhi 110017, India',
    phone: '+91 11 2651 5050',
    services: ['Comprehensive Stroke Center', 'Intensive Care', 'Neurosurgery', 'Rehabilitation Services'],
    imageUrl: '/max hospital.jpg',
    imageHint: 'modern medical center delhi',
  },
  {
    id: '7',
    name: 'Kokilaben Dhirubhai Ambani Hospital - Mumbai',
    address: 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai, Maharashtra 400053, India',
    phone: '+91 22 3066 6666',
    services: ['Multi-Speciality', 'Robotic Surgery', 'Cancer Care', 'Stroke Program'],
    imageUrl: '/kokila.avif',
    imageHint: 'large hospital mumbai',
  },
  {
    id: '8',
    name: 'Lilavati Hospital and Research Centre - Mumbai',
    address: 'A-791, Bandra Reclamation, Bandra (West), Mumbai, Maharashtra 400050, India',
    phone: '+91 22 2675 1000',
    services: ['Neurology', 'Cardiology', 'Oncology', 'Emergency Room'],
    imageUrl: '/lilavita.jpg',
    imageHint: 'research hospital mumbai',
  },
  {
    id: '9',
    name: 'Breach Candy Hospital Trust - Mumbai',
    address: '60 A, Bhulabhai Desai Road, Breach Candy, Cumballa Hill, Mumbai, Maharashtra 400026, India',
    phone: '+91 22 2367 1888',
    services: ['Critical Care', 'Diagnostic Services', 'Surgical Specialties', 'Neurology'],
    imageUrl: '/breach.avif',
    imageHint: 'classic hospital mumbai',
  },
  {
    id: '10',
    name: 'Indraprastha Apollo Hospitals - Delhi',
    address: 'Delhi Mathura Road, Sarita Vihar, New Delhi, Delhi 110076, India',
    phone: '+91 11 2692 5858',
    services: ['Advanced Stroke Unit', 'Organ Transplant', 'Cardiac Sciences', 'Neurosciences'],
    imageUrl: '/indraprastha.avif',
    imageHint: 'apollo hospital delhi',
  },
  {
    id: '11',
    name: 'Fortis Escorts Heart Institute - Delhi',
    address: 'Okhla Road, Sukhdev Vihar Metro Station, New Friends Colony, New Delhi, Delhi 110025, India',
    phone: '+91 11 4713 5000',
    services: ['Cardiac Care', 'Emergency Services', 'Neurology', 'Vascular Surgery'],
    imageUrl: '/fortis.jpg',
    imageHint: 'heart institute delhi',
  },
  {
    id: '12',
    name: 'Sir Ganga Ram Hospital - Delhi',
    address: 'Sir Ganga Ram Hospital Marg, Old Rajinder Nagar, Rajinder Nagar, New Delhi, Delhi 110060, India',
    phone: '+91 11 2575 0000',
    services: ['Multi-Speciality Care', 'Research Wing', 'Emergency Department', 'Stroke Clinic'],
    imageUrl: '/sir ganga.jpeg',
    imageHint: 'ganga ram hospital delhi',
  }
];

export const healthcareServicesList: HealthcareService[] = [
  {
    id: 'home-nurse-booking',
    title: 'Home Nurse Booking',
    description: 'Book certified nurses for dedicated in-home medical care and support.',
    icon: UserRoundPlus,
    href: '/healthcare-services/home-nurse-booking',
    cta: 'Book a Nurse',
  },
  {
    id: 'doctor-visits-at-home',
    title: 'Doctor Visits at Home',
    description: 'Schedule convenient at-home consultations with qualified doctors.',
    icon: Home,
    href: '/healthcare-services/doctor-visits',
    cta: 'Schedule Visit',
  },
  {
    id: 'video-consultation',
    title: 'Video Consultation',
    description: 'Connect with doctors virtually for consultations from the comfort of your home.',
    icon: Video,
    href: '/healthcare-services/video-consultation',
    cta: 'Consult Online',
  },
  {
    id: 'pharma-medication-delivery',
    title: 'Pharma & Medication Delivery',
    description: 'Order prescribed medications and healthcare products delivered to your doorstep.',
    icon: Truck,
    href: '/healthcare-services/pharma-delivery',
    cta: 'Order Medicines',
  },
  {
    id: 'at-home-blood-tests',
    title: 'At-Home Blood Tests',
    description: 'Book lab technicians for sample collection at home and get digital reports.',
    icon: TestTube2,
    href: '/healthcare-services/lab-tests',
    cta: 'Book a Test',
  },
];

export const sampleNurses: Nurse[] = [
  {
    id: 'nurse001',
    name: 'Priya Sharma',
    specializations: ['Stroke Rehabilitation', 'Geriatric Care', 'Post-operative Care'],
    experienceYears: 8,
    hourlyRate: 1200, // INR
    availability: 'Mon-Sat, 8am-6pm',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'female nurse professional',
    bio: 'Priya is a dedicated and compassionate nurse with extensive experience in helping stroke patients regain independence. She is skilled in mobility assistance, medication management, and providing emotional support.',
    verifiedLicense: true,
  },
  {
    id: 'nurse002',
    name: 'Amit Singh',
    specializations: ['Neurological Care', 'Wound Management', 'Palliative Care'],
    experienceYears: 12,
    hourlyRate: 1500, // INR
    availability: 'Flexible, including evenings',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'male nurse smiling',
    bio: 'Amit is a highly skilled nurse specializing in complex neurological conditions. He is proficient in advanced wound care techniques and offers compassionate palliative support.',
    verifiedLicense: true,
  },
  {
    id: 'nurse003',
    name: 'Sunita Reddy',
    specializations: ['Cardiac Care', 'Diabetes Management', 'Elderly Support'],
    experienceYears: 6,
    hourlyRate: 1100, // INR
    availability: 'Weekdays, 9am-5pm',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'nurse with stethoscope',
    bio: 'Sunita has a strong background in cardiac care and diabetes education. She is passionate about empowering patients and their families with the knowledge to manage chronic conditions effectively at home.',
    verifiedLicense: true,
  },
  {
    id: 'nurse004',
    name: 'Rajesh Kumar',
    specializations: ['Emergency Care', 'ICU Experience', 'Ventilator Management'],
    experienceYears: 10,
    hourlyRate: 1400,
    availability: 'Mon-Fri, 7am-7pm',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'male nurse focused',
    bio: 'Rajesh is an experienced critical care nurse, adept at handling emergency situations and managing patients requiring intensive care.',
    verifiedLicense: true,
  },
  {
    id: 'nurse005',
    name: 'Anjali Mehta',
    specializations: ['Pediatric Care', 'Special Needs Support', 'Home Infusion Therapy'],
    experienceYears: 7,
    hourlyRate: 1300,
    availability: 'Flexible, Weekends preferred',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'female nurse gentle',
    bio: 'Anjali specializes in pediatric home care and is skilled in supporting children with special needs. She is also experienced in home infusion therapies.',
    verifiedLicense: true,
  },
  {
    id: 'nurse006',
    name: 'Vikram Patel',
    specializations: ['Orthopedic Care', 'Post-Surgery Rehabilitation', 'Pain Management'],
    experienceYears: 9,
    hourlyRate: 1350,
    availability: 'Tue-Sat, 10am-6pm',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'nurse assisting patient',
    bio: 'Vikram has a strong background in orthopedic nursing, assisting patients with recovery after surgery and managing chronic pain conditions.',
    verifiedLicense: true,
  },
  {
    id: 'nurse007',
    name: 'Deepa Iyer',
    specializations: ['Mental Health Support', 'Counseling', 'Dementia Care'],
    experienceYears: 11,
    hourlyRate: 1600,
    availability: 'Mon, Wed, Fri, 9am-3pm',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'female nurse empathetic',
    bio: 'Deepa is a compassionate nurse focusing on mental health and dementia care, providing both medical support and counseling to patients and families.',
    verifiedLicense: true,
  },
  {
    id: 'nurse008',
    name: 'Mohan Das',
    specializations: ['General Nursing', 'Elderly Companionship', 'Medication Reminders'],
    experienceYears: 5,
    hourlyRate: 1000,
    availability: 'Daily, 4-hour shifts',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'senior care nurse',
    bio: 'Mohan provides general nursing care and companionship for the elderly, ensuring medication adherence and daily well-being checks.',
    verifiedLicense: true,
  }
];

// Sample Doctors Data
export const sampleDoctors: Doctor[] = [
  {
    id: 'doc001',
    fullName: 'Dr. Anita Sharma',
    specialty: 'General Physician',
    yearsOfExperience: 15,
    languagesSpoken: ['English', 'Hindi', 'Telugu'],
    ratings: 4.7,
    verifiedLicense: true,
    profilePictureUrl: 'https://placehold.co/300x300.png',
    imageHint: 'female doctor smiling',
    locationDescription: 'Serves Mehdipatnam, Tolichowki, and Langar Houz.',
    consultationFee: 800,
    availability: 'Mon-Sat, 9am-1pm & 4pm-7pm',
    bio: 'Dr. Sharma is a highly experienced GP focusing on family health and chronic disease management. Known for her compassionate approach.',
    videoConsultationFee: 600,
    videoAvailabilitySlots: ['Mon 10am-11am', 'Wed 3pm-4pm', 'Fri 11am-12pm']
  },
  {
    id: 'doc002',
    fullName: 'Dr. Vikram Singh Rathore',
    specialty: 'Neurologist',
    yearsOfExperience: 12,
    languagesSpoken: ['English', 'Hindi'],
    ratings: 4.9,
    verifiedLicense: true,
    profilePictureUrl: 'https://placehold.co/300x300.png',
    imageHint: 'male doctor professional',
    locationDescription: 'Available for home visits across Hyderabad (central & west zones).',
    consultationFee: 1500,
    availability: 'Mon, Wed, Fri, 10am-4pm (by appointment)',
    bio: 'Specializes in stroke recovery, epilepsy, and movement disorders. Committed to providing comprehensive neurological care at home.',
    videoConsultationFee: 1200,
    videoAvailabilitySlots: ['Tue 2pm-3pm', 'Thu 4pm-5pm (Next Week)']
  },
  {
    id: 'doc003',
    fullName: 'Dr. Priya Reddy',
    specialty: 'Geriatrician',
    yearsOfExperience: 10,
    languagesSpoken: ['English', 'Telugu'],
    ratings: 4.6,
    verifiedLicense: true,
    profilePictureUrl: 'https://placehold.co/300x300.png',
    imageHint: 'female doctor attentive',
    locationDescription: 'Focuses on elderly care in Ameerpet, Banjara Hills, and Jubilee Hills.',
    consultationFee: 1000,
    availability: 'Tue, Thu, Sat, 11am-5pm',
    bio: 'Dr. Reddy is passionate about elderly care, providing holistic assessments and management plans for age-related health issues.',
    videoConsultationFee: 750,
    videoAvailabilitySlots: ['Mon 9am-10am', 'Sat 10am-11am']
  },
  {
    id: 'doc004',
    fullName: 'Dr. Arjun Mehta',
    specialty: 'Cardiologist',
    yearsOfExperience: 18,
    languagesSpoken: ['English', 'Hindi', 'Gujarati'],
    ratings: 4.8,
    verifiedLicense: true,
    profilePictureUrl: 'https://placehold.co/300x300.png',
    imageHint: 'male doctor serious',
    locationDescription: 'Pan-Hyderabad coverage for emergency cardiac consultations.',
    consultationFee: 2000,
    availability: 'Available on call for critical cases.',
    bio: 'Experienced cardiologist providing expert consultations for heart-related conditions.',
    videoConsultationFee: 1800,
    videoAvailabilitySlots: ['Flexible (On Request)']
  },
  {
    id: 'doc005',
    fullName: 'Dr. Sunaina Gupta',
    specialty: 'Speech Therapist',
    yearsOfExperience: 7,
    languagesSpoken: ['English', 'Hindi'],
    ratings: 4.5,
    verifiedLicense: true,
    profilePictureUrl: 'https://placehold.co/300x300.png',
    imageHint: 'female doctor friendly',
    locationDescription: 'Specializes in post-stroke speech rehabilitation.',
    consultationFee: 900,
    availability: 'By appointment',
    bio: 'Dr. Gupta helps patients recover speech and swallowing abilities post-stroke, using evidence-based therapies.',
    videoConsultationFee: 700,
    videoAvailabilitySlots: ['Mon 2pm-3pm', 'Wed 10am-11am', 'Fri 2pm-3pm']
  },
  {
    id: 'doc006',
    fullName: 'Dr. Ramesh Iyer',
    specialty: 'Psychiatrist',
    yearsOfExperience: 20,
    languagesSpoken: ['English', 'Tamil', 'Hindi'],
    ratings: 4.9,
    verifiedLicense: true,
    profilePictureUrl: 'https://placehold.co/300x300.png',
    imageHint: 'male doctor listening',
    locationDescription: 'Mental health support for patients and caregivers.',
    consultationFee: 1800,
    availability: 'Tue & Thu, 5pm-8pm',
    bio: 'Dr. Iyer provides counseling and psychiatric support for individuals coping with the emotional and mental impact of stroke.',
    videoConsultationFee: 1500,
    videoAvailabilitySlots: ['Tue 6pm-7pm', 'Thu 7pm-8pm']
  }
];


export const sampleConsultationTypes: ConsultationType[] = [
  { id: 'general', name: 'General Consultation', description: 'For general health check-ups or non-specific symptoms.' },
  { id: 'neurology', name: 'Neurology Follow-up', description: 'Follow-up for existing neurological conditions or stroke recovery.' },
  { id: 'speech_therapy', name: 'Speech Therapy Assessment', description: 'Initial assessment for speech-related issues post-stroke.' },
  { id: 'mental_wellness', name: 'Mental Wellness Check-in', description: 'Consultation for emotional support and mental well-being.' },
  { id: 'cardiology', name: 'Cardiology Consultation', description: 'For heart-related concerns and post-stroke cardiac care.' },
];

export const samplePharmacyProducts: PharmacyProduct[] = [
  {
    id: 'med001',
    productName: 'Aspirin 75mg Tablets (Strip of 10)',
    category: 'Blood Thinners',
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'aspirin tablets',
    price: 25, // INR
    inStock: true,
    description: 'Low-dose aspirin helps prevent blood clots. Commonly prescribed after a stroke.',
    tags: ['stroke recovery', 'heart health', 'blood thinner'],
    prescriptionRequired: true,
  },
  {
    id: 'med002',
    productName: 'Omega-3 Fish Oil Capsules (60 Capsules)',
    category: 'Supplements',
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'fish oil capsules',
    price: 450,
    inStock: true,
    description: 'Supports brain health and cardiovascular function. May aid in stroke recovery.',
    tags: ['brain health', 'supplement', 'omega 3'],
    prescriptionRequired: false,
  },
  {
    id: 'med003',
    productName: 'Paracetamol 500mg Tablets (Strip of 15)',
    category: 'Pain Relief',
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'paracetamol tablets',
    price: 30,
    inStock: true,
    description: 'Provides relief from mild to moderate pain and fever.',
    tags: ['pain relief', 'fever'],
    prescriptionRequired: false,
  },
  {
    id: 'med004',
    productName: 'Vitamin D3 Capsules (Weekly Dose - 4 Capsules)',
    category: 'Supplements',
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'vitamin D3 capsules',
    price: 120,
    inStock: true,
    description: 'Supports bone health and immune function. Important for overall well-being.',
    tags: ['vitamin D', 'bone health', 'supplement'],
    prescriptionRequired: false,
  },
  {
    id: 'med005',
    productName: 'Atorvastatin 10mg Tablets (Strip of 10)',
    category: 'Cholesterol Control',
    imageUrl: 'https://placehold.co/300x200.png',
    imageHint: 'cholesterol tablets',
    price: 80,
    inStock: true,
    description: 'Used to lower cholesterol and reduce the risk of heart disease and stroke.',
    tags: ['cholesterol', 'heart health', 'stroke prevention'],
    prescriptionRequired: true,
  },
];
